Prototype of model explanation via LIME with help of extractive summary
---

---

In [59]:
import numpy as np

import tensorflow_datasets as tfds
import tensorflow as tf
from tensorflow import keras

import time

tfds.disable_progress_bar()

In [66]:
now = time.strftime("%Y-%m-%d_%H:%M")

In [67]:
import logging
import sys

logging.basicConfig(
    level=logging.DEBUG, 
    format='[{%(filename)s:%(lineno)d} %(levelname)s - %(message)s',
    handlers=[
        logging.FileHandler(filename=f'../../data/logs/v1-{now}.log'),
        logging.StreamHandler(sys.stdout)
    ]
)

l = logging.getLogger('prototype')
l.critical("Logging LIME with new TF model")

[{<ipython-input-67-d59e77e64a5c>:14} CRITICAL - Logging LIME with new TF model


---

Model-related
---

In [61]:
def load_model():
    """
    Define a function that loads a model to be explained and returns its instance
    """
    
    return keras.models.load_model("../../raw-data/lstm-model-sigmoid")    

In [62]:
model = _load_model()
l.info("Model loaded")

[{<ipython-input-62-619c90ce7f16>:2} INFO - Model loaded


In [63]:
model.predict(["hahahahahahahahahaha this is the most boring film I have ever seen"])

array([[0.0706619]], dtype=float32)

In [64]:
model.predict_proba(["hahahahahahahahahaha this is the funniest film I have ever seen"])

array([[0.948632]], dtype=float32)

---

Explanation
---

#### 1. Preparation

In [72]:
from lime import lime_text

from sumy.parsers.plaintext import PlaintextParser
from sumy.nlp.tokenizers import Tokenizer
from sumy.nlp.stemmers import Stemmer
from sumy.utils import get_stop_words
from sumy.summarizers.text_rank import TextRankSummarizer

import os

from functools import reduce

In [73]:
INPUT_DIR = "/home/tomasmizera/school/diploma/src/data/reviews"

LANGUAGE = "english"
SENTENCES_COUNT = 6
TOP_FEATURES_COUNT = 10 

In [74]:
summarizer = TextRankSummarizer(Stemmer(LANGUAGE))
summarizer.stop_words = get_stop_words('english')

In [75]:
explanator = lime_text.LimeTextExplainer(class_names=['positive', 'negative'])

---

### 2. Execution

In [36]:
l.info("Starting an algorithm")

[{<ipython-input-36-9e84a1d64b6b>:1} INFO - Starting an algorithm


In [37]:
# helper function to join summary
def _get_data_from_summary(summary):
    return ' '.join(list(map(lambda sentence: str(sentence), summary)))

In [39]:
# define a decorator to log execusion time
# inspired by https://medium.com/pythonhive/python-decorator-to-measure-the-execution-time-of-methods-fa04cb6bb36d

def timeit(method):
    def timed(*args, **kw):
        timed.calls += 1
        ts = time.time()
        result = method(*args, **kw)
        te = time.time()
        timed.time_taken += (te - ts) * 1000
        return result
    timed.calls = 0
    timed.time_taken = 0
    return timed

In [51]:
@timeit
def _predict_proba(_input):
    """
    Define a function that accepts array of instances and returns a probability for each class 
    _input - 1d array of instances
    Returns 2d array of [num of instances] x [num of classes]
    """
    # TODO: implement this!
    # Mocked to simulate what LIME does in the background https://github.com/marcotcr/lime/issues/35
#     l.debug("Called _predict_proba with input: " + str(_input))
#     return np.array(5000 * [[0.4, 0.6]])

    return np.array(list(zip(1-model.predict(_input), model.predict(_input))))

In [41]:
model.predict(["worst"])

array([[-1.4426748]], dtype=float32)

In [52]:
def _explain_instance(_file, _explanator):
    explanation = _explanator.explain_instance(_file, _predict_proba, num_features=TOP_FEATURES_COUNT)
    l.info('_explain_instance took:  %2.2f ms' % \
                  (_predict_proba.time_taken))
    l.info(f'_explain_instance called {_predict_proba.calls} times')
    _predict_proba.calls = 0
    _predict_proba.time_taken = 0
    
    return explanation

In [48]:
test_input = "This is the most ridiculous film I have ever seen"

In [53]:
expl = _explain_instance(test_input, explanator)

[{<ipython-input-52-6b94f3b454a8>:3} INFO - _explain_instance took:  906.03 ms
[{<ipython-input-52-6b94f3b454a8>:5} INFO - _explain_instance called 1 times


In [55]:
expl.as_list()

[('This', -0.08454352874338847)]

**Some examples of perturbed text**: \[ ..., ' great hm', ' great ', ' great hm', '  hm', '  ', '  hm', '  ', '  ', '  ', '  ', 'not great ', '  ', '  hm', '  ', '  ', 'not great ', '  ', ' great ', ' great ', '  hm', '  ', ' great ', 'not  hm', ' great hm', ' great ', ' great hm', '  hm', 'not  ', '  hm', 'not  ', ' great hm', 'not great ', ' great ', '  ', '  ', '  hm', '  ', '  ', '  ', 'not  hm', 'not  ', 'not great ', 'not  hm', 'not  hm', 'not great ', 'not  hm', '  ', ' great ', '  ', '  hm', 'not  hm', '  ', '  ', ' great ', '  ', '  ', ' great ', 'not  ', 'not  hm', ' great ', 'not  ', 'not  ', 'not  hm', 'not  ', '  ', 'not great ', '  hm', ' great hm', '  hm', '  ', '  ', 'not  hm', '  hm', 'not  ', '  ', ' great hm', 'not  ', ' great hm', 'not  hm', 'not  ', 'not  hm', '  ', ' great ', '  hm', ' great ', 'not  hm', 'not  ', 'not  ', ' great hm', 'not  hm', '  hm', '  hm', ' great ', '  ', 'not great ', '  hm', 'not great ', '  ', '  ', 'not  hm', 'not great ', '  ', '  ', ' great hm', 'not  hm', 'not  hm', ' great ', ' great hm', '  ', 'not  hm', ' great ', '  hm', ' great ', 'not great ', '  ', '  ', ' great hm', ' great hm', '  ', ' great ', 'not  hm', ' great ', 'not  ', ' great ', 'not great ', ' great ', 'not  ', 'not great ', '  ', '  ', '  ', 'not  ', ' great hm', ' great hm', '  ', '  ', 'not great ', '  ', '  ', 'not  ', ' great ', ' great ', 'not great ', '  ', '  ', '  ', '  ', '  ', '  ', '  hm', '  hm', 'not  ', 'not  hm', 'not  ', '  ', ' great ', '  hm', ' great hm', '  ', '  ', '  ', ' great hm', '  ', '  ', 'not  hm', '  ', ' great hm', ' great hm', ' great ', '  ', '  ', 'not  ', '  ', 'not  ', ' great hm', 'not great ', ' great hm', 'not  hm', 'not great ', 'not  ', 'not great ', '  ', 'not great ', '  hm', 'not  ', ' great ', '  ', '  ', ' great ', '  hm', 'not  ', 'not  ', 'not  ', '  ', ' great hm', ' great hm', ' great ', ' great ', 'not great ', ' great ', '  ', 'not great ', 'not great ', '  ', 'not  ', ' great ', ' great ', '  ', '  ', ' great ', 'not  ', ' great ', '  ', '  ', ' great ', 'not  hm', 'not  ', '  ', 'not great ', '  ', '  ', '  ', 'not great ', 'not great ', '  ', '  hm', '  hm', 'not  hm', 'not great ', ' great ', 'not  ', '  ', 'not  hm', 'not great ', 'not  ', 'not great ', 'not  hm', 'not  ', 'not  hm', ' great hm', ' great ', '  hm', '  ', '  hm', '  ', 'not  ', ' great ', '  ', '  hm', 'not  hm', 'not great ', '  ', '  ', ' great ', '  ', '  ', 'not  ', 'not  ', ' great ', '  ', 'not  hm', '  ', ' great hm', '  ', '  ', '  ', ' great ', ' great ', ' great ', ' great ', ' great ', '  hm', 'not  ', ' great ', 'not  hm', '  ', ' great hm', 'not great ', '  hm', '  hm', 'not  hm', 'not  ', 'not great ', '  ', '  ', '  ', 'not  ', '  ', ' great ', '  ', 'not great ', '  ', 'not  ', '  ', '  hm', ' great ', '  ', 'not  ', ' great hm', '  ', ' great ', 'not great ', '  ']

In [ ]:
# im_words = expl.as_list() TODO: when predict_proba will work
# $store -r a
im_words = a

In [ ]:
def input_from_files(path_to_files):
    """
    Loads all readable files in path_to_files directory
    Returns np.array with each files content as a separate element
    """
    
    def _read_text_file(filepath):
        with open(filepath, 'r') as f:
            return reduce(lambda a, b: a + b, f.readlines())
    
    files_it = os.scandir(path_to_files)
    files_contents = {}
    
    for file in files_it:
        if file.is_file(): 
            files_contents[file.name] = _read_text_file(file.path)
        
    return files_contents

In [ ]:
npInput = input_from_files(INPUT_DIR)

In [ ]:
def _summarize_doc_custom(_summarizer, _instance, _explanation):
    """
    Returns summary with altered weights based on explanation
    _summarizer - summy summarizer instance
    _instance - instance content string
    _explanation - LIME explanation
    """
    
    def _create_weight_graph(_summarizer, _instance_doc):
        return _summarizer.rate_sentences(_instance_doc)
    
    def _count_factor(_sentence, _explanation_words_weight) -> float: # returns boosting factor for sentence
        factor = 1.0
        exp_words = list(map(lambda x: x[0], _explanation_words_weight))
        for word in _sentence.words:
            if word in exp_words:
                factor += abs(_explanation_words_weight[exp_words.index(word)][1])        
        return factor
    
    parser = PlaintextParser.from_string(_instance, Tokenizer(LANGUAGE))
    graph = _create_weight_graph(_summarizer, parser.document)
    
    for sentence in graph.keys():
        factor = _count_factor(sentence, _explanation.as_list())
        graph[sentence] = graph[sentence] * factor # TODO: normalize the factor value
        
    resulting_summary = _summarizer._get_best_sentences(parser.document.sentences, SENTENCES_COUNT, graph)
    
    return resulting_summary

In [ ]:
def _summary_to_string(_summary):
    if len(_summary) <= 0:
        return ""
    
    summary_str = str(_summary[0])
    i = 1
    
    while(i < len(_summary)):
        summary_str += ' ' + str(_summary[i])
        i += 1
        
    return summary_str

In [ ]:
def create_explanation_summaries(_instance_map, _explanator, _summarizer):
    """
    Returns summaries for all input elements
    _instance_map - map containing instance name and its content
    _explanator - LIME explanator instance
    _summarizer - summy summarizer instance
    """
    
    summaries = {}
    
    for instance in _instance_map.keys():
        explanation = _explain_instance(_instance_map[instance])
        summary = _summarize_doc_custom(_summarizer, _instance_map[instance], explanation)
        summaries[instance] = (_summary_to_string(summary), explanation.as_list())

    return summaries

In [ ]:
def create_simple_summaries(_instance_map, _summarizer):
    """
    Returns summaries for all input instances
    _instance_map - map containing instance name and its content
    _summarizer - summy summarizer instance
    """
    
    summaries = {}
    
    for instance in _instance_map.keys():
        _parser = PlaintextParser.from_string(_instance_map[instance], Tokenizer(LANGUAGE))
        summaries[instance] = _summary_to_string(_summarizer(_parser.document, SENTENCES_COUNT))
    
    return summaries

In [ ]:
from IPython.core.display import display, HTML

highlight_start = f'<mark style="background-color:rgba(250, 100, 0, {0.00})">'
highlight_end = '</mark>'
text = ''.join([highlight_start, "Hellloo!", highlight_end])

display(HTML(text))

In [ ]:
def display_highlighted_summary(summary_pair):
    pass

In [ ]:
create_explanation_summaries(npInput, explanator, summarizer);

In [ ]:
create_simple_summaries(npInput, summarizer);

TODO:
- [x] find a good pytorch/tf LSTM text classification model ~ maybe check datasets in LIME paper
- [x] create predict_proba based on the type of the framework
- [ ] predict on created summaries ~ automatically -> (possible: save summaries to files and then load and pass them just as normal instance) 
- [ ] refactor process to not store everything in RAM, rather put intermediate results to files
- [ ] highlighting of important words from any summary (maybe save both, str summary and Sentence type summary - from sumy)
- [ ] extract it to separate script
- [ ] add better logging (more logs in this version)
- [ ] build and test quantitative experiment pipeline
- [ ] maybe find better dataset (longer texts) for data and train another model for it
- [ ] run quantitative experiment on all instances
- [ ] pick several (~6) explanations for user-study